/*nfortunately MySQL does not support 
SQL check constraints. You can define them in your DDL query for compatibility 
reasons but they are just ignored.*/

CREATE TABLE DEVICE(
PLACE VARCHAR(50),
ID CHAR(3),
OWNER_FIRST_NAME VARCHAR(50),
OWNER_LAST_NAME VARCHAR(50),
PRIMARY KEY(ID)
);

CREATE TABLE MEASUREMENTS(
DEVICE_ID CHAR(3),
MEASUREMENT_DATE DATE,
MEASUREMENT_TIME TIME,
TEMPERATURE INT,
HUMIDITY INT,
PRIMARY KEY(DEVICE_ID, MEASUREMENT_DATE, MEASUREMENT_TIME),
FOREIGN KEY(DEVICE_ID) REFERENCES DEVICE(ID),
CONSTRAINT CHK_TEMPERATURE CHECK (TEMPERATURE>-30 AND TEMPERATURE<70),
CONSTRAINT CHK_HUMIDITY CHECK (HUMIDITY>=0 AND HUMIDITY<=100)
);


#Select the last measurement in the database for a specific place
/*SELECT MEASUREMENT_TIME, TEMPERATURE, HUMIDITY
FROM NEW_MEASUREMENTS 
WHERE MEASUREMENT_DATE=(SELECT MEASUREMENT_DATE 
						FROM NEW_MEASUREMENTS 
						ORDER BY MEASUREMENT_DATE DESC 
						LIMIT 1) AND PLACE='TEE' 
ORDER BY MEASUREMENT_TIME DESC
LIMIT 1;*/
